# Generated by Django 5.2.4 on 2025-07-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_avion_remove_vuelo_capacidad_vuelo_avion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='documento',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
