# Generated by Django 5.2.4 on 2025-07-27 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_pasajero_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='asientos',
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('ocupado', 'Ocupado')], default='disponible', max_length=20)),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.vuelo')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='asiento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.asiento'),
        ),
    ]
