# Generated by Django 5.2.4 on 2025-07-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_reserva_asientos_asiento_reserva_asiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='avion',
            name='informacion_tecnica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avion',
            name='layout_asientos',
            field=models.JSONField(default=dict),
        ),
    ]
