# Generated by Django 5.2.4 on 2025-08-01 14:53

from django.db import migrations

def load_initial_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Avion = apps.get_model('gestion', 'Avion')
    Vuelo = apps.get_model('gestion', 'Vuelo')
    Pasajero = apps.get_model('gestion', 'Pasajero')
    Asiento = apps.get_model('gestion', 'Asiento')
    Reserva = apps.get_model('gestion', 'Reserva')

    # Aviones
    avion1 = Avion.objects.create(modelo='Boeing 737', capacidad=180, layout_asientos={
        "filas": [
            {"fila": 1, "asientos": [{"numero": "1A"}, {"numero": "1B"}, {"numero": "1C"}]},
            {"fila": 2, "asientos": [{"numero": "2A"}, {"numero": "2B"}, {"numero": "2C"}]}
        ]
    })
    avion2 = Avion.objects.create(modelo='Airbus A320', capacidad=150, layout_asientos={
        "filas": [
            {"fila": 1, "asientos": [{"numero": "1A"}, {"numero": "1B"}]},
            {"fila": 2, "asientos": [{"numero": "2A"}, {"numero": "2B"}]}
        ]
    })

    # Vuelos
    vuelo1 = Vuelo.objects.create(origen='Buenos Aires', destino='Cordoba', fecha_salida='2025-09-01 10:00:00', fecha_llegada='2025-09-01 11:30:00', precio=150.00, avion=avion1)
    vuelo2 = Vuelo.objects.create(origen='Cordoba', destino='Mendoza', fecha_salida='2025-09-05 15:00:00', fecha_llegada='2025-09-05 16:00:00', precio=120.00, avion=avion2)

    # Crear asientos para los vuelos
    for fila in avion1.layout_asientos.get('filas', []):
        for asiento_info in fila.get('asientos', []):
            Asiento.objects.create(vuelo=vuelo1, numero=asiento_info['numero'])
    
    for fila in avion2.layout_asientos.get('filas', []):
        for asiento_info in fila.get('asientos', []):
            Asiento.objects.create(vuelo=vuelo2, numero=asiento_info['numero'])

    # Pasajeros
    user1 = User.objects.create_user(username='pasajero1@example.com', email='pasajero1@example.com', password='password')
    pasajero1 = Pasajero.objects.create(user=user1, nombre='Juan', apellido='Perez', documento='12345678', email='pasajero1@example.com', telefono='1122334455')
    
    user2 = User.objects.create_user(username='pasajero2@example.com', email='pasajero2@example.com', password='password')
    pasajero2 = Pasajero.objects.create(user=user2, nombre='Maria', apellido='Gomez', documento='87654321', email='pasajero2@example.com', telefono='5544332211')

    # Asientos y Reservas
    asiento1_vuelo1 = Asiento.objects.get(vuelo=vuelo1, numero='1A')
    asiento1_vuelo1.estado = 'reservado'
    asiento1_vuelo1.save()
    Reserva.objects.create(vuelo=vuelo1, pasajero=pasajero1, asiento=asiento1_vuelo1)

    asiento2_vuelo2 = Asiento.objects.get(vuelo=vuelo2, numero='2B')
    asiento2_vuelo2.estado = 'reservado'
    asiento2_vuelo2.save()
    Reserva.objects.create(vuelo=vuelo2, pasajero=pasajero2, asiento=asiento2_vuelo2)


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_avion_informacion_tecnica_avion_layout_asientos'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, migrations.RunPython.noop),
    ]
