# Generated by Django 5.2.4 on 2025-08-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20250801_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='documento',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
