# Generated by Django 5.2.7 on 2025-10-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_passenger_last_name_flighthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='flighthistory',
            name='price_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
