# Generated by Django 5.2.7 on 2025-10-12 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_flighthistory_price_paid_flighthistory_seat_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_name', models.CharField(max_length=100, unique=True)),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='model',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='type',
        ),
        migrations.AddField(
            model_name='airplane',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airplane',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airplane',
            name='model_name',
            field=models.CharField(default='Default Model', max_length=100),
        ),
        migrations.AddField(
            model_name='airplane',
            name='registration_number',
            field=models.CharField(default='dd3ddd1c6b484475a184', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='airplane',
            name='technical_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airplane',
            name='year_of_manufacture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airplane',
            name='seat_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airline.seatlayout'),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airline.seattype'),
        ),
        migrations.CreateModel(
            name='SeatLayoutPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.CharField(max_length=2)),
                ('seat_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='airline.seatlayout')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.seattype')),
            ],
            options={
                'unique_together': {('seat_layout', 'row', 'column')},
            },
        ),
    ]
