# Generated by Django 5.2.7 on 2025-10-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0004_seatlayout_seattype_remove_airplane_columns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='registration_number',
            field=models.CharField(default='75d99084bf774e40942e', max_length=20, unique=True),
        ),
    ]
