# Generated by Django 5.2.7 on 2025-10-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0005_alter_airplane_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='registration_number',
            field=models.CharField(default='94e4b64cbf8545dc97fb', max_length=20, unique=True),
        ),
    ]
