# Generated by Django 5.2.7 on 2025-10-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('vuelo', 'asiento'), ('vuelo', 'pasajero')},
        ),
    ]
